name: Run monetdb-perl test suite

on:
  push:
  pull_request:
  # monday morning 01:23
  schedule:
    - cron: 23 1 * * 1

jobs:
  runtests:
    runs-on: ubuntu-latest
    env:
      DBI_DSN: dbi:monetdb:database=demo

    services:
      monetdb:
        image: monetdb/monetdb:latest
        ports:
          - 50000:50000

    steps:

      - uses: actions/checkout@v2

      - name: Run Unit-Tests
        run: |
          set -x -e
          ./runtests.sh
