name: Run monetdb-perl test suite

on: [push]

jobs:
  runtests:
    runs-on: ubuntu-latest
    env:
      DBFARM: /var/lib/monetdb

    steps:
    - uses: actions/checkout@v2

    - name: Install MonetDB
      run: |
          set -x -e
          lsb_release -c -s
          sudo apt-get -qq update
          sudo apt-get -qq install y software-properties-common curl make libdbi-perl
          curl -s https://www.monetdb.org/downloads/MonetDB-GPG-KEY | sudo apt-key add -
          sudo add-apt-repository "deb http://dev.monetdb.org/downloads/deb/ $(lsb_release -c -s) monetdb"
          sudo apt-get -qq update
          sudo apt-get -qq install -qqy monetdb5-server

    - name: Run Unit-Tests
      run: |
          set -x -e
          ./runtests.sh
